name: docs

on:
  push:
    branches:
      - main
      - fergus/doc-debug
    paths:
      - docs/**.md
      - docs/**.jl

jobs:
  docs:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            # add Buckets.jl
            Pkg.add(url="https://github.com/fjebaker/Buckets.jl")
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
