name: docs

on:
  push:
    branches:
      - main
      - fergus/doc-debug
    paths:
      - docs/**.md
      - docs/**.jl
    workflow_dispatch: null

jobs:
  docs:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'
      - run: |
          julia -e 'import Pkg ; Pkg.update() ; Pkg.Registry.add("https://github.com/astro-group-bristol/AstroRegistry")'
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
